# PostgreSQL Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/homesphere_db
spring.datasource.username=postgres
spring.datasource.password=Prasad

# Hibernate / JPA Settings (Automatically creates tables)
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true